### ISSUE TITLE
create main customer page

### ISSUE THREAD

**Issue by Mahmoud-zino** [physio-praxis/myPhysio#33]
## TODOs
- [x] Create a table of Cards with the info about the customer (all fields from the database) and it's animals (all fields from the database)
- [x] Create an add new customer page with customer validation.
- [x] Create an Add customer button that will open the Add new customer page.
- [x] Create the search field (only visually)
